version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5172:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=conscius
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=conscius
    ports:
      - "3306:3306"